version: '3.5'

services:
  pg:
    container_name: postgres
    restart: always
    build: 
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 5432:5432
  
  client:
    container_name: react
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${REACT_APP_PORT}:80
    links: 
      - server
    depends_on:
      - server

  server:
    container_name: express
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile
    links: 
      - pg
    depends_on: 
      - pg
    environment: 
      SSL_PASSPHRASE: ${SSL_PASSPHRASE}
      DB_HOST: pg
    expose:
      - ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
      - "1000:443"